export const STORAGE = {
    USER: "STORAGE:USER",
    SECURITY: "STORAGE:SECURITY",
    CART: "STORAGE:CART",
    APPLE: "STORAGE:APPLE",
    AUCTION: "STORAGE:AUCTION",
    CATEGORY: "STORAGE:CATEGORY",
    POSTS: "STORAGE:POSTS",
    REMEMBER_EMAIL: "REMEMBER:EMAIL",
}