const ACTION_TYPE = {
    APP_LOADER: "APP::LOADER",
    APP_LOADER_COVER: "APP::LOADER::COVER",
    LOGGED_IN: "LOGGED::IN",
    ACTION_LOGINSETTER: "ACTION::LOGINSETTER",
    ACTION_LOGOUTSETTER: "ACTION::LOGOUTSETTER",
    AUTH_POPUP: "AUTH::POPUP",
    APP_NAVIGATION: "APP:SYSTEM:APP_NAVIGATION",
    DEEP_LINK: "APP:SYSTEM:DEEP_LINK",
    APP_POST_COLLECTION: "APP:SYSTEM:APP_POST_COLLECTION"
}

export default ACTION_TYPE;